CREATE USER C##JDBCSJ IDENTIFIED BY JDBCSJ;
GRANT CONNECT, RESOURCE TO C##JDBCSJ;
ALTER USER C##JDBCSJ DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

DROP TABLE BOOK;
CREATE TABLE BOOK (
	BOOK_ID NUMBER PRIMARY KEY,
	TITLE VARCHAR2(100) NOT NULL,
	AUTHOR VARCHAR2(50) NOT NULL,
	PUBLISHER VARCHAR2(50),
	PRICE NUMBER DEFAULT 0
);

COMMENT ON COLUMN BOOK.BOOK_ID IS '도서 번호';
COMMENT ON COLUMN BOOK.TITLE IS '도서명';
COMMENT ON COLUMN BOOK.AUTHOR IS '저자명';
COMMENT ON COLUMN BOOK.PUBLISHER IS '출판사';
COMMENT ON COLUMN BOOK.PRICE IS '가격';

DROP SEQUENCE SEQ_BOOKID;
CREATE SEQUENCE SEQ_BOOKID
	START WITH 100
	NOCYCLE
	NOCACHE;


INSERT INTO BOOK VALUES (SEQ_BOOKID.NEXTVAL, '이것이 자바다', '신용권, 임경균', '한빛미디어', 34200);
INSERT INTO BOOK VALUES (SEQ_BOOKID.NEXTVAL, '난생처음 파이썬 프로그래밍', '우재남, 최민아', '한빛미디어', 24000);
INSERT INTO BOOK VALUES (SEQ_BOOKID.NEXTVAL, '혼자 공부하는 네트워크', '강민철', '한빛미디어', 25200);
COMMIT;